sudo: required
language: python
dist: xenial  # Required for Python 3.7
cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install --progress-bar off .[tensorflow-cpu]
  - pip install pylint==2.3.1 flake8==3.7.7
  - pip install pytest
  - pip install coverage codecov

script:
  # Linting
  - pylint texar/ examples/
  - flake8 texar/ examples/
  # Unit tests
  - pytest
  # Test coverage
  - coverage run -m pytest

after_success:
  - codecov

notifications:
  email: false
