os: linux
language: python
dist: xenial  # Required for Python 3.7
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - TENSORFLOW_VER="2.0.0"
  - TENSORFLOW_VER="2.1.0"

install:
  - pip install --upgrade pip
  - pip install --progress-bar off tensorflow==$TENSORFLOW_VER
  - pip install pylint==2.4.4 flake8==3.7.9;
  - pip install pytest
  - pip install coverage codecov

script:
  # Linting
  - pylint texar/ examples/
  - flake8 texar/ examples/
  # Unit tests & Test coverage
  - coverage run -m pytest

after_success:
  - codecov

notifications:
  email: false
