os: linux
language: python
dist: xenial  # Required for Python 3.7
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - TENSORFLOW_VER="2.0.0"
  - TENSORFLOW_VER="2.1.0"

install:
  - pip install --upgrade pip
  - pip install --progress-bar off tensorflow==$TENSORFLOW_VER
  - pip install --progress-bar off .[tensorflow]
  - if [[ $TENSORFLOW_VER == "2.1.0" ]]; then
      pip install pylint==2.4.4 flake8==3.7.9;
    fi
  - pip install pytest
  - pip install coverage codecov

script:
  # Linting (only for TensorFlow version 2.1.0 to save time)
  - if [[ $TENSORFLOW_VER == "2.1.0" ]]; then
      pylint texar/ examples/;
    fi
  - if [[ $TENSORFLOW_VER == "2.1.0" ]]; then
      flake8 texar/ examples/;
    fi
  # Unit tests & Test coverage
  - coverage run -m pytest

after_success:
  - codecov

jobs:
  include:
    - stage: docs
      python: "3.7"
      install:
        - pip install --upgrade pip
        - pip install --progress-bar off -r requirements.txt
        # Install library required for spellcheck
        - sudo apt-get install libenchant1c2a myspell-en-us
        - pip install --progress-bar off -r docs/requirements.txt
      script:
        - cd docs
        # Build documents
        - sphinx-build -W -b html -d _build/doctrees . _build/html
        # Check for typos
        - sphinx-build -W -b spelling -d _build/doctrees . _build/spelling

  fast_finish: true
  exclude:
    - python: "3.6"
      env: TENSORFLOW_VER="2.1.0"

notifications:
  email: false
